//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beauty
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_import
    {
        public int id { get; set; }
        public string NameService { get; set; }
        public string MainImage { get; set; }
        public string Duration { get; set; }
        public Nullable<int> Cost { get; set; }
        public Nullable<int> Discount { get; set; }
        public int CostDiscount { get; set; }
    }
}
